### PR TITLE
[source]: Added several attributes

### PR DESCRIPTION
**Pull request by andrey-helldar**
@Laravel-Lang/laravel-lang, hi!

Added several attributes from the real project. I think it might be useful to other developers.

### CODE REVIEW

**Comment by mohamedsabil83** [comment]
Agree. I have already added some of them to some projects before.

**Comment by andrey-helldar** [comment]
@Laravel-Lang/laravel-lang, if you have other names for fields that can be used in different projects, feel free to add them here.

This project is not related to Laravel translations out of the box, so we can do whatever we want.

**Comment by Oleksandr-Moik** [comment]
Why I did not see this project early 🤯

**Comment by andrey-helldar** [comment]
@Oleksandr-Moik, i don't know

You can see that: https://github.com/Laravel-Lang/common/blob/main/composer.json#L51

**Comment by Oleksandr-Moik** [comment]
Oh)

I think I can add more attributes from my list that will be useful, but a little later😉

**Comment by andrey-helldar** [comment]
No problem)

This project is a helper and was intended as a repository for common field names. Or not common ones :)

**Comment by mohamedsabil83** [comment]
I reviewed the Arabic translations, and everything is fine.

**Pull request merged**
