### PR TITLE
[ar] Translate missing phrases

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Thank you ☺️

**Comment by mohamedsabil83** [comment]
You're welcome 😎

**Comment by andrey-helldar** [comment]
If your application uses field names that are not in this repository, you can add.

In this repository, we add everything that may be useful to developers :)

**Comment by mohamedsabil83** [comment]
Yep, and by sharing and translating our fields, we help each other 👍🏽

**Comment by andrey-helldar** [comment]
Exactly! 🙂

**Pull request merged**
